[package]
name = "mutate-macros"
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {workspace = true, features = ["span-locations"]}
quote.workspace = true
syn.workspace = true

[features]
